[package]
name = "berncrypt"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9"
x25519-dalek = { version = "2.0.1", features = ["getrandom"] }
chacha20poly1305 = { version = "0.10" }
aead = "0.5"
anyhow = "1.0"

hkdf = "0.11.0"
blake2 = "0.9.2"
